version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: gobarber_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: boeing747
      POSTGRES_DB: gobarber
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: gobarber_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
